#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fill Privacy Policy translations for all languages
"""
import json

# Read English as reference
with open('src/lib/i18n/translations/en.json', 'r', encoding='utf-8') as f:
    en_data = json.load(f)

# Comprehensive Privacy Policy translations
privacy_translations = {
    'fr': {
        'title': 'Politique de Confidentialité',
        'subtitle': 'Votre vie privée est importante pour nous. Cette politique explique comment nous collectons, utilisons et protégeons vos informations personnelles sur notre plateforme de marché B2B.',
        'lastUpdated': 'Dernière mise à jour: 5 octobre 2025',
        'welcome': 'Notre Engagement envers la Confidentialité',
        'welcomeDesc': "Chez Fruit Habibi, nous nous engageons à protéger votre vie privée et à assurer la sécurité de vos informations personnelles. Cette Politique de Confidentialité explique nos pratiques concernant la collecte, l'utilisation et la protection des informations lorsque vous utilisez notre plateforme de marché B2B. Nous croyons en la transparence et vous donner le contrôle sur vos données personnelles.",
        'questionsAboutPrivacy': 'Questions ou Préoccupations sur la Confidentialité?',
        'questionsDesc': "Si vous avez des questions sur cette Politique de Confidentialité ou sur la façon dont nous traitons vos informations personnelles, n'hésitez pas à contacter notre équipe de confidentialité. Nous sommes là pour vous aider.",
        'contactSupport': 'Contacter l\'Équipe de Confidentialité',
        'helpCenter': 'Centre d\'Aide',
        'section1Title': '1. Informations que Nous Collectons',
        'section1Content': 'Informations Personnelles:\n\n• Informations de contact professionnel (nom, email, téléphone, adresse)\n• Détails d\'enregistrement d\'entreprise et d\'identification fiscale\n• Informations de paiement et bancaires (traitées de manière sécurisée)\n• Documents de vérification d\'identité\n• Listes et descriptions de produits\n• Dossiers de communication avec d\'autres utilisateurs\n\nInformations Techniques:\n\n• Adresses IP et informations sur les appareils\n• Type et version du navigateur\n• Modèles d\'utilisation et interactions avec la plateforme\n• Cookies et technologies de suivi similaires\n• Données de localisation (si fournies ou détectées)\n\nNous collectons ces informations pour fournir nos services, vérifier les identités, traiter les transactions et améliorer la fonctionnalité de notre plateforme.',
        'section2Title': '2. Comment Nous Utilisons Vos Informations',
        'section2Content': 'Prestation de Services:\n\n• Création et maintenance de votre compte\n• Traitement des transactions et paiements\n• Facilitation de la communication entre utilisateurs\n• Fourniture de support client\n• Vérification des identifiants professionnels\n\nAmélioration de la Plateforme:\n\n• Analyse des modèles d\'utilisation pour améliorer les services\n• Développement de nouvelles fonctionnalités\n• Recherche et analyses\n• Personnalisation de l\'expérience utilisateur\n• Prévention de la fraude et des abus\n\nConformité Légale:\n\n• Respect des exigences réglementaires\n• Réponse aux demandes légales\n• Protection de nos droits et intérêts\n• Assurance de la sécurité de la plateforme\n• Maintien des dossiers de transaction\n\nNous utilisons vos informations uniquement à des fins commerciales légitimes et en conformité avec les lois applicables.',
        'section3Title': '3. Partage d\'Informations',
        'section3Content': 'Nous pouvons partager vos informations dans les circonstances suivantes:\n\nAvec d\'Autres Utilisateurs:\n• Informations de contact professionnel à des fins de transaction\n• Listes et descriptions de produits\n• Informations de profil public (si vous choisissez de les rendre publiques)\n\nAvec les Prestataires de Services:\n• Processeurs de paiement pour la gestion des transactions\n• Partenaires d\'expédition et logistique\n• Fournisseurs de stockage cloud et d\'hébergement\n• Outils de support client\n• Services d\'analyse et de marketing\n\nExigences Légales:\n• Lorsque requis par la loi ou le processus légal\n• Pour protéger nos droits et notre propriété\n• En cas d\'urgence pour protéger la sécurité\n• Pour se conformer aux demandes gouvernementales\n\nTransferts d\'Entreprise:\n• En cas de fusion, acquisition ou vente d\'actifs\n• Avec votre consentement explicite à d\'autres fins\n\nNous ne vendons jamais vos informations personnelles à des tiers à des fins de marketing.',
        'section4Title': '4. Sécurité des Données',
        'section4Content': 'Mesures de Sécurité:\n\n• Chiffrement des données en transit et au repos\n• Serveurs sécurisés avec mises à jour de sécurité régulières\n• Contrôles d\'accès et systèmes d\'authentification\n• Audits et évaluations de sécurité réguliers\n• Formation des employés sur la protection des données\n\nSafeguards Techniques:\n\n• Chiffrement SSL/TLS pour toutes les communications\n• Authentification multi-facteurs pour les opérations sensibles\n• Procédures de sauvegarde et de récupération d\'urgence régulières\n• Systèmes de détection et de prévention d\'intrusion\n• Pratiques de codage sécurisées et tests de vulnérabilité\n\nRéponse aux Violations de Données:\n\n• Enquête et confinement immédiats\n• Notification aux utilisateurs affectés dans les 72 heures\n• Coopération avec les forces de l\'ordre si nécessaire\n• Mise en œuvre de mesures de sécurité supplémentaires\n• Mises à jour régulières sur les progrès de résolution\n\nBien que nous mettions en œuvre des mesures de sécurité de niveau industrie, aucun système n\'est sécurisé à 100%. Nous travaillons continuellement à améliorer nos pratiques de sécurité.',
        'section5Title': '5. Conservation des Données',
        'section5Content': 'Périodes de Conservation:\n\nInformations de Compte:\n• Comptes actifs: Conservées tant que le compte est actif\n• Comptes fermés: Conservées pendant 7 ans pour la conformité légale\n• Comptes suspendus: Conservées jusqu\'à résolution ou fermeture permanente\n\nDonnées de Transaction:\n• Dossiers de paiement: 7 ans pour la conformité fiscale et légale\n• Journaux de communication: 3 ans pour la résolution de litiges\n• Listes de produits: Jusqu\'à la fermeture du compte ou la suppression\n\nDonnées Techniques:\n• Fichiers journaux: 1 an pour la surveillance de sécurité et de performance\n• Données d\'analyse: 2 ans pour l\'amélioration de la plateforme\n• Cookies: Comme spécifié dans notre politique de cookies\n\nExigences Légales:\n\n• Dossiers financiers: 7 ans minimum\n• Vérification d\'identité: 5 ans après la fermeture du compte\n• Procédures légales: Jusqu\'à résolution plus le délai de prescription applicable\n\nVous pouvez demander la suppression de certaines informations personnelles, sous réserve des exigences légales et opérationnelles.',
        'section6Title': '6. Vos Droits et Choix',
        'section6Content': 'Vos Droits:\n\nAccès et Portabilité:\n• Demander des copies de vos informations personnelles\n• Recevoir des données dans un format portable\n• Comprendre comment nous utilisons vos informations\n\nCorrection et Mises à Jour:\n• Corriger les informations personnelles inexactes\n• Mettre à jour les informations de votre compte\n• Modifier vos préférences de confidentialité\n\nSuppression et Restriction:\n• Demander la suppression d\'informations personnelles\n• Restreindre le traitement de vos données\n• S\'opposer à certaines activités de traitement de données\n\nPréférences de Communication:\n• Se désabonner des communications marketing\n• Choisir les préférences de notification\n• Gérer les paramètres de cookies\n\nComment Exercer Vos Droits:\n\n• Contactez-nous via nos canaux de support\n• Utilisez les paramètres du compte pour les préférences de base\n• Soumettez des demandes formelles pour les changements complexes\n• Fournissez une identification pour la vérification de sécurité\n\nNous répondrons à vos demandes dans les 30 jours, sous réserve de vérification et d\'exigences légales.',
        'section7Title': '7. Transferts Internationaux de Données',
        'section7Content': 'Opérations Mondiales:\n\n• Notre plateforme dessert les utilisateurs du monde entier\n• Les données peuvent être transférées à travers les frontières internationales\n• Nous assurons une protection adéquate pour tous les transferts\n\nMécanismes de Transfert:\n\n• Clauses Contractuelles Standard (CCS)\n• Décisions d\'adéquation par les autorités compétentes\n• Règles d\'Entreprise Contraignantes le cas échéant\n• Consentement de l\'utilisateur pour les transferts spécifiques\n\nConformité Régionale:\n\nUnion Européenne (RGPD):\n• Conformité complète aux exigences du RGPD\n• Délégué à la Protection des Données nommé\n• Principes de protection de la vie privée dès la conception mis en œuvre\n\nÉtats-Unis:\n• Conformité aux lois fédérales et d\'État applicables\n• Conformité CCPA et autres lois sur la confidentialité des États\n\nAutres Juridictions:\n• Conformité aux lois locales sur la confidentialité le cas échéant\n• Examen régulier des changements réglementaires\n\nNous nous assurons que les transferts internationaux répondent aux normes les plus élevées de protection des données.',
        'section8Title': '8. Cookies et Suivi',
        'section8Content': 'Types de Cookies:\n\nCookies Essentiels:\n• Requis pour la fonctionnalité de la plateforme\n• Fonctionnalités d\'authentification et de sécurité\n• Gestion du panier d\'achat et de la session\n\nCookies de Performance:\n• Analyses et statistiques d\'utilisation\n• Surveillance des performances de la plateforme\n• Suivi des erreurs et débogage\n\nCookies Fonctionnels:\n• Préférences et paramètres utilisateur\n• Langue et localisation\n• Fonctionnalités d\'expérience utilisateur améliorées\n\nCookies Marketing:\n• Contenu publicitaire et promotionnel\n• Analyse du comportement des utilisateurs\n• Communications marketing ciblées\n\nGestion des Cookies:\n\n• Bannière de consentement aux cookies lors de la première visite\n• Contrôle granulaire des catégories de cookies\n• Mécanismes de désinscription faciles\n• Examen régulier de l\'utilisation des cookies\n\nVous pouvez gérer les préférences de cookies via les paramètres de votre navigateur ou nos outils de gestion des cookies.',
        'section9Title': '9. Confidentialité des Enfants',
        'section9Content': 'Restrictions d\'Âge:\n\n• Notre plateforme n\'est pas destinée aux enfants de moins de 16 ans\n• Nous ne collectons pas sciemment d\'informations auprès d\'enfants\n• Les comptes professionnels nécessitent une vérification adulte\n\nDroits Parentaux:\n\n• Les parents peuvent demander des informations sur le compte de leur enfant\n• Droit d\'examiner et de supprimer les informations de l\'enfant\n• Notification de collecte de données auprès d\'enfants\n\nSi nous découvrons que nous avons collecté des informations auprès d\'un enfant sans consentement parental, nous supprimerons ces informations immédiatement.',
        'section10Title': '10. Services Tiers',
        'section10Content': 'Services Intégrés:\n\nTraitement des Paiements:\n• Passerelles de paiement sécurisées\n• Processeurs conformes PCI DSS\n• Partage de données limité pour le traitement des transactions\n\nExpédition et Logistique:\n• Partenaires d\'expédition internationaux\n• Services de suivi et de livraison\n• Données douanières et de conformité\n\nAnalyses et Marketing:\n• Fournisseurs d\'analyses de sites web\n• Outils d\'automatisation marketing\n• Systèmes de gestion de la relation client\n\nPolitiques Tiers:\n\n• Chaque service a sa propre politique de confidentialité\n• Nous vérifions les partenaires pour la conformité à la confidentialité\n• Partage de données limité à des fins spécifiques\n• Examen régulier des pratiques des tiers\n\nNous ne sommes pas responsables des pratiques de confidentialité des services tiers. Les utilisateurs doivent examiner les politiques de confidentialité des tiers avant d\'utiliser les services intégrés.',
        'section11Title': '11. Modifications de la Politique de Confidentialité',
        'section11Content': 'Mises à Jour de la Politique:\n\n• Nous pouvons mettre à jour cette politique de confidentialité périodiquement\n• Les changements importants seront communiqués par email\n• Les politiques mises à jour seront publiées sur notre site web\n• Les versions précédentes sont disponibles sur demande\n\nProcessus de Notification:\n\n• Notification par email pour les changements matériels\n• Bannière de site web pour les mises à jour importantes\n• Notification de compte pour les changements significatifs\n• Avis de 30 jours pour les modifications substantielles\n\nDroits des Utilisateurs:\n\n• Droit d\'examiner les politiques mises à jour\n• Option d\'accepter ou de rejeter les changements\n• Capacité de fermer le compte en cas de désaccord avec les changements\n• L\'utilisation continue constitue une acceptation\n\nNous encourageons les utilisateurs à examiner régulièrement notre politique de confidentialité pour rester informés de nos pratiques.',
        'section12Title': '12. Informations de Contact',
        'section12Content': 'Délégué à la Protection des Données:\n\nEmail: privacy@fruithabibi.com\nTéléphone: +1 (555) 123-4567\nAdresse: Bureau de Protection des Données, Fruit Habibi Inc., 123 Business Plaza, Suite 456, San Francisco, CA 94105, USA\n\nDemandes Générales de Confidentialité:\n\nEmail: support@fruithabibi.com\nCentre d\'Aide: /help\nFormulaire de Contact: /contact\n\nDemandes Légales:\n\nEmail: legal@fruithabibi.com\nPour les demandes d\'application de la loi et de processus légal\n\nTemps de Réponse:\n\n• Demandes générales: 48 heures\n• Demandes de droits de confidentialité: 30 jours\n• Demandes légales: Selon les exigences de la loi\n• Incidents de sécurité: 72 heures pour notification\n\nNous nous engageons à répondre à toutes les préoccupations de confidentialité rapidement et minutieusement.'
    },
    'ar': {
        'title': 'سياسة الخصوصية',
        'subtitle': 'خصوصيتك مهمة بالنسبة لنا. توضح هذه السياسة كيفية جمع معلوماتك الشخصية واستخدامها وحمايتها على منصة السوق B2B الخاصة بنا.',
        'lastUpdated': 'آخر تحديث: 5 أكتوبر 2025',
        'welcome': 'التزامنا بالخصوصية',
        'welcomeDesc': 'في Fruit Habibi، نحن ملتزمون بحماية خصوصيتك وضمان أمان معلوماتك الشخصية. توضح سياسة الخصوصية هذه ممارساتنا فيما يتعلق بجمع المعلومات واستخدامها وحمايتها عند استخدام منصة السوق B2B الخاصة بنا. نؤمن بالشفافية وإعطائك السيطرة على بياناتك الشخصية.',
        'questionsAboutPrivacy': 'أسئلة أو مخاوف حول الخصوصية؟',
        'questionsDesc': 'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه أو كيفية تعاملنا مع معلوماتك الشخصية، فلا تتردد في الاتصال بفريق الخصوصية لدينا. نحن هنا للمساعدة.',
        'contactSupport': 'اتصل بفريق الخصوصية',
        'helpCenter': 'مركز المساعدة',
        'section1Title': '1. المعلومات التي نجمعها',
        'section1Content': 'المعلومات الشخصية:\n\n• معلومات الاتصال التجارية (الاسم، البريد الإلكتروني، الهاتف، العنوان)\n• تفاصيل تسجيل الأعمال وتحديد الهوية الضريبية\n• معلومات الدفع والمصرفية (معالجة بشكل آمن)\n• مستندات التحقق من الهوية\n• قوائم المنتجات والأوصاف\n• سجلات التواصل مع المستخدمين الآخرين\n\nالمعلومات التقنية:\n\n• عناوين IP ومعلومات الجهاز\n• نوع المتصفح والإصدار\n• أنماط الاستخدام والتفاعلات مع المنصة\n• ملفات تعريف الارتباط وتقنيات التتبع المماثلة\n• بيانات الموقع (إذا تم توفيرها أو اكتشافها)\n\nنجمع هذه المعلومات لتقديم خدماتنا، والتحقق من الهويات، ومعالجة المعاملات، وتحسين وظائف منصتنا.',
        'section2Title': '2. كيفية استخدامنا لمعلوماتك',
        'section2Content': 'تقديم الخدمات:\n\n• إنشاء حسابك وصيانته\n• معالجة المعاملات والمدفوعات\n• تسهيل التواصل بين المستخدمين\n• تقديم دعم العملاء\n• التحقق من بيانات الاعتماد التجارية\n\nتحسين المنصة:\n\n• تحليل أنماط الاستخدام لتحسين الخدمات\n• تطوير ميزات ووظائف جديدة\n• إجراء البحوث والتحليلات\n• تخصيص تجربة المستخدم\n• منع الاحتيال والإساءة\n\nالامتثال القانوني:\n\n• تلبية المتطلبات التنظيمية\n• الاستجابة للطلبات القانونية\n• حماية حقوقنا ومصالحنا\n• ضمان أمان المنصة\n• الحفاظ على سجلات المعاملات\n\nنستخدم معلوماتك فقط لأغراض تجارية مشروعة ووفقًا للقوانين المعمول بها.',
        'section3Title': '3. مشاركة المعلومات',
        'section3Content': 'قد نشارك معلوماتك في الحالات التالية:\n\nمع المستخدمين الآخرين:\n• معلومات الاتصال التجارية لأغراض المعاملات\n• قوائم المنتجات والأوصاف\n• معلومات الملف الشخصي العام (إذا اخترت جعلها عامة)\n\nمع مقدمي الخدمات:\n• معالجات الدفع لمعالجة المعاملات\n• شركاء الشحن واللوجستيات\n• مزودي التخزين السحابي والاستضافة\n• أدوات دعم العملاء\n• خدمات التحليلات والتسويق\n\nالمتطلبات القانونية:\n• عند الحاجة بموجب القانون أو الإجراءات القانونية\n• لحماية حقوقنا وممتلكاتنا\n• في حالات الطوارئ لحماية السلامة\n• للامتثال لطلبات الحكومة\n\nنقل الأعمال:\n• في حالة الاندماج أو الاستحواذ أو بيع الأصول\n• بموافقتك الصريحة لأغراض أخرى\n\nلا نبيع أبدًا معلوماتك الشخصية لأطراف ثالثة لأغراض التسويق.',
        'section4Title': '4. أمان البيانات',
        'section4Content': 'تدابير الأمان:\n\n• تشفير البيانات أثناء النقل والراحة\n• خوادم آمنة مع تحديثات أمنية منتظمة\n• ضوابط الوصول وأنظمة المصادقة\n• عمليات تدقيق وتقييم أمنية منتظمة\n• تدريب الموظفين على حماية البيانات\n\nالضمانات التقنية:\n\n• تشفير SSL/TLS لجميع الاتصالات\n• المصادقة متعددة العوامل للعمليات الحساسة\n• إجراءات النسخ الاحتياطي والتعافي من الكوارث المنتظمة\n• أنظمة كشف ومنع التسلل\n• ممارسات الترميز الآمنة واختبار الثغرات\n\nالاستجابة لانتهاكات البيانات:\n\n• التحقيق والاحتواء الفوري\n• إشعار المستخدمين المتأثرين خلال 72 ساعة\n• التعاون مع إنفاذ القانون إذا لزم الأمر\n• تنفيذ تدابير أمنية إضافية\n• تحديثات منتظمة حول تقدم الحل\n\nبينما ننفذ تدابير أمنية معيارية في الصناعة، لا يوجد نظام آمن بنسبة 100%. نعمل باستمرار على تحسين ممارساتنا الأمنية.',
        'section5Title': '5. الاحتفاظ بالبيانات',
        'section5Content': 'فترات الاحتفاظ:\n\nمعلومات الحساب:\n• الحسابات النشطة: محفوظة طالما أن الحساب نشط\n• الحسابات المغلقة: محفوظة لمدة 7 سنوات للامتثال القانوني\n• الحسابات المعلقة: محفوظة حتى الحل أو الإغلاق الدائم\n\nبيانات المعاملات:\n• سجلات الدفع: 7 سنوات للامتثال الضريبي والقانوني\n• سجلات الاتصال: 3 سنوات لحل النزاعات\n• قوائم المنتجات: حتى إغلاق الحساب أو الإزالة\n\nالبيانات التقنية:\n• ملفات السجل: سنة واحدة لمراقبة الأمان والأداء\n• بيانات التحليلات: سنتان لتحسين المنصة\n• ملفات تعريف الارتباط: كما هو محدد في سياسة ملفات تعريف الارتباط الخاصة بنا\n\nالمتطلبات القانونية:\n\n• السجلات المالية: 7 سنوات كحد أدنى\n• التحقق من الهوية: 5 سنوات بعد إغلاق الحساب\n• الإجراءات القانونية: حتى الحل بالإضافة إلى قانون التقادم المعمول به\n\nيمكنك طلب حذف بعض المعلومات الشخصية، مع مراعاة المتطلبات القانونية والتشغيلية.',
        'section6Title': '6. حقوقك وخياراتك',
        'section6Content': 'حقوقك:\n\nالوصول والقابلية للنقل:\n• طلب نسخ من معلوماتك الشخصية\n• استلام البيانات بتنسيق قابل للنقل\n• فهم كيفية استخدامنا لمعلوماتك\n\nالتصحيح والتحديثات:\n• تصحيح المعلومات الشخصية غير الدقيقة\n• تحديث معلومات حسابك\n• تعديل تفضيلات الخصوصية الخاصة بك\n\nالحذف والقيود:\n• طلب حذف المعلومات الشخصية\n• تقييد معالجة بياناتك\n• الاعتراض على أنشطة معالجة البيانات معينة\n\nتفضيلات الاتصال:\n• إلغاء الاشتراك في الاتصالات التسويقية\n• اختيار تفضيلات الإشعارات\n• إدارة إعدادات ملفات تعريف الارتباط\n\nكيفية ممارسة حقوقك:\n\n• اتصل بنا من خلال قنوات الدعم الخاصة بنا\n• استخدم إعدادات الحساب للتفضيلات الأساسية\n• قدم طلبات رسمية للتغييرات المعقدة\n• قدم تحديد الهوية للتحقق الأمني\n\nسنرد على طلباتك خلال 30 يومًا، مع مراعاة التحقق والمتطلبات القانونية.',
        'section7Title': '7. نقل البيانات الدولية',
        'section7Content': 'العمليات العالمية:\n\n• تخدم منصتنا المستخدمين في جميع أنحاء العالم\n• قد يتم نقل البيانات عبر الحدود الدولية\n• نضمن حماية كافية لجميع عمليات النقل\n\nآليات النقل:\n\n• البنود التعاقدية القياسية (SCCs)\n• قرارات الكفاية من قبل السلطات المختصة\n• قواعد الشركة الملزمة حيثما ينطبق\n• موافقة المستخدم للتحويلات المحددة\n\nالامتثال الإقليمي:\n\nالاتحاد الأوروبي (GDPR):\n• الامتثال الكامل لمتطلبات GDPR\n• تعيين مسؤول حماية البيانات\n• تنفيذ مبادئ الخصوصية بالتصميم\n\nالولايات المتحدة:\n• الامتثال للقوانين الفيدرالية وحكومات الولايات المعمول بها\n• الامتثال لـ CCPA وقوانين خصوصية الولايات الأخرى\n\nالولايات القضائية الأخرى:\n• الامتثال لقوانين الخصوصية المحلية حيثما ينطبق\n• مراجعة منتظمة للتغييرات التنظيمية\n\nنضمن أن عمليات النقل الدولية تلبي أعلى معايير حماية البيانات.',
        'section8Title': '8. ملفات تعريف الارتباط والتتبع',
        'section8Content': 'أنواع ملفات تعريف الارتباط:\n\nملفات تعريف الارتباط الأساسية:\n• مطلوبة لوظائف المنصة\n• ميزات المصادقة والأمان\n• إدارة سلة التسوق والجلسة\n\nملفات تعريف الارتباط للأداء:\n• التحليلات وإحصائيات الاستخدام\n• مراقبة أداء المنصة\n• تتبع الأخطاء والتشخيص\n\nملفات تعريف الارتباط الوظيفية:\n• تفضيلات وإعدادات المستخدم\n• اللغة والتعريب\n• ميزات تجربة المستخدم المحسنة\n\nملفات تعريف الارتباط التسويقية:\n• المحتوى الإعلاني والترويجي\n• تحليل سلوك المستخدم\n• الاتصالات التسويقية المستهدفة\n\nإدارة ملفات تعريف الارتباط:\n\n• لافتة موافقة ملفات تعريف الارتباط في الزيارة الأولى\n• تحكم دقيق في فئات ملفات تعريف الارتباط\n• آليات إلغاء الاشتراك سهلة\n• مراجعة منتظمة لاستخدام ملفات تعريف الارتباط\n\nيمكنك إدارة تفضيلات ملفات تعريف الارتباط من خلال إعدادات المتصفح أو أدوات إدارة ملفات تعريف الارتباط الخاصة بنا.',
        'section9Title': '9. خصوصية الأطفال',
        'section9Content': 'قيود العمر:\n\n• منصتنا غير مخصصة للأطفال دون سن 16\n• لا نجمع معلومات من الأطفال عن علم\n• تتطلب الحسابات التجارية التحقق من البالغين\n\nحقوق الوالدين:\n\n• يمكن للوالدين طلب معلومات حول حساب طفلهم\n• الحق في مراجعة وحذف معلومات الطفل\n• إشعار جمع البيانات من الأطفال\n\nإذا اكتشفنا أننا جمعنا معلومات من طفل دون موافقة الوالدين، فسنحذف هذه المعلومات على الفور.',
        'section10Title': '10. خدمات الطرف الثالث',
        'section10Content': 'الخدمات المتكاملة:\n\nمعالجة المدفوعات:\n• بوابات الدفع الآمنة\n• معالجات متوافقة مع PCI DSS\n• مشاركة بيانات محدودة لمعالجة المعاملات\n\nالشحن واللوجستيات:\n• شركاء الشحن الدوليين\n• خدمات التتبع والتسليم\n• بيانات الجمارك والامتثال\n\nالتحليلات والتسويق:\n• مزودي تحليلات المواقع\n• أدوات أتمتة التسويق\n• أنظمة إدارة علاقات العملاء\n\nسياسات الطرف الثالث:\n\n• لكل خدمة سياسة خصوصية خاصة بها\n• نتحقق من الشركاء للامتثال للخصوصية\n• مشاركة بيانات محدودة لأغراض محددة\n• مراجعة منتظمة لممارسات الطرف الثالث\n\nنحن لسنا مسؤولين عن ممارسات الخصوصية لخدمات الطرف الثالث. يجب على المستخدمين مراجعة سياسات الخصوصية للطرف الثالث قبل استخدام الخدمات المتكاملة.',
        'section11Title': '11. تغييرات سياسة الخصوصية',
        'section11Content': 'تحديثات السياسة:\n\n• قد نحدث سياسة الخصوصية هذه بشكل دوري\n• سيتم إبلاغ التغييرات المهمة عبر البريد الإلكتروني\n• سيتم نشر السياسات المحدثة على موقعنا على الويب\n• الإصدارات السابقة متاحة عند الطلب\n\nعملية الإشعار:\n\n• إشعار بالبريد الإلكتروني للتغييرات المادية\n• لافتة موقع الويب للتحديثات المهمة\n• إشعار الحساب للتغييرات المهمة\n• إشعار 30 يومًا للتعديلات الجوهرية\n\nحقوق المستخدمين:\n\n• الحق في مراجعة السياسات المحدثة\n• خيار قبول أو رفض التغييرات\n• القدرة على إغلاق الحساب في حالة عدم الموافقة على التغييرات\n• الاستخدام المستمر يشكل قبولاً\n\nنشجع المستخدمين على مراجعة سياسة الخصوصية الخاصة بنا بانتظام للبقاء على اطلاع بممارساتنا.',
        'section12Title': '12. معلومات الاتصال',
        'section12Content': 'مسؤول حماية البيانات:\n\nالبريد الإلكتروني: privacy@fruithabibi.com\nالهاتف: +1 (555) 123-4567\nالعنوان: مكتب حماية البيانات، Fruit Habibi Inc.، 123 Business Plaza، Suite 456، San Francisco، CA 94105، USA\n\nالاستفسارات العامة حول الخصوصية:\n\nالبريد الإلكتروني: support@fruithabibi.com\nمركز المساعدة: /help\nنموذج الاتصال: /contact\n\nالطلبات القانونية:\n\nالبريد الإلكتروني: legal@fruithabibi.com\nلطلبات إنفاذ القانون والإجراءات القانونية\n\nأوقات الاستجابة:\n\n• الاستفسارات العامة: 48 ساعة\n• طلبات حقوق الخصوصية: 30 يومًا\n• الطلبات القانونية: حسب متطلبات القانون\n• حوادث الأمان: 72 ساعة للإشعار\n\nنحن ملتزمون بالرد على جميع مخاوف الخصوصية بسرعة وبشكل شامل.'
    },
    'hi': {
        'title': 'गोपनीयता नीति',
        'subtitle': 'आपकी गोपनीयता हमारे लिए महत्वपूर्ण है। यह नीति बताती है कि हम अपने B2B मार्केटप्लेस प्लेटफॉर्म पर आपकी व्यक्तिगत जानकारी कैसे एकत्र, उपयोग और सुरक्षित करते हैं।',
        'lastUpdated': 'अंतिम अपडेट: 5 अक्टूबर 2025',
        'welcome': 'गोपनीयता के प्रति हमारी प्रतिबद्धता',
        'welcomeDesc': 'Fruit Habibi में, हम आपकी गोपनीयता की सुरक्षा और आपकी व्यक्तिगत जानकारी की सुरक्षा सुनिश्चित करने के लिए प्रतिबद्ध हैं। यह गोपनीयता नीति हमारे B2B मार्केटप्लेस प्लेटफॉर्म का उपयोग करते समय जानकारी के संग्रह, उपयोग और सुरक्षा के संबंध में हमारी प्रथाओं को समझाती है। हम पारदर्शिता में विश्वास करते हैं और आपको अपने व्यक्तिगत डेटा पर नियंत्रण देते हैं।',
        'questionsAboutPrivacy': 'गोपनीयता के बारे में प्रश्न या चिंताएं?',
        'questionsDesc': 'यदि इस गोपनीयता नीति या हमारे व्यक्तिगत जानकारी को संभालने के तरीके के बारे में आपके कोई प्रश्न हैं, तो कृपया हमारी गोपनीयता टीम से संपर्क करने में संकोच न करें। हम मदद के लिए यहां हैं।',
        'contactSupport': 'गोपनीयता टीम से संपर्क करें',
        'helpCenter': 'सहायता केंद्र',
        'section1Title': '1. हम जो जानकारी एकत्र करते हैं',
        'section1Content': 'व्यक्तिगत जानकारी:\n\n• व्यावसायिक संपर्क जानकारी (नाम, ईमेल, फोन, पता)\n• व्यावसायिक पंजीकरण और कर पहचान विवरण\n• भुगतान और बैंकिंग जानकारी (सुरक्षित रूप से संसाधित)\n• पहचान सत्यापन दस्तावेज\n• उत्पाद सूचियां और विवरण\n• अन्य उपयोगकर्ताओं के साथ संचार रिकॉर्ड\n\nतकनीकी जानकारी:\n\n• IP पते और डिवाइस जानकारी\n• ब्राउज़र प्रकार और संस्करण\n• उपयोग पैटर्न और प्लेटफॉर्म इंटरैक्शन\n• कुकीज़ और समान ट्रैकिंग तकनीकें\n• स्थान डेटा (यदि प्रदान किया गया या पता लगाया गया)\n\nहम अपनी सेवाएं प्रदान करने, पहचान सत्यापित करने, लेनदेन संसाधित करने और अपने प्लेटफॉर्म की कार्यक्षमता में सुधार करने के लिए यह जानकारी एकत्र करते हैं।',
        'section2Title': '2. हम आपकी जानकारी का उपयोग कैसे करते हैं',
        'section2Content': 'सेवा प्रावधान:\n\n• आपके खाते को बनाना और बनाए रखना\n• लेनदेन और भुगतान संसाधित करना\n• उपयोगकर्ताओं के बीच संचार सुविधाजनक बनाना\n• ग्राहक सहायता प्रदान करना\n• व्यावसायिक क्रेडेंशियल सत्यापित करना\n\nप्लेटफॉर्म सुधार:\n\n• सेवाओं में सुधार के लिए उपयोग पैटर्न का विश्लेषण\n• नई सुविधाओं और कार्यक्षमता का विकास\n• अनुसंधान और विश्लेषण करना\n• उपयोगकर्ता अनुभव को व्यक्तिगत बनाना\n• धोखाधड़ी और दुरुपयोग को रोकना\n\nकानूनी अनुपालन:\n\n• नियामक आवश्यकताओं को पूरा करना\n• कानूनी अनुरोधों का जवाब देना\n• अपने अधिकारों और हितों की सुरक्षा\n• प्लेटफॉर्म सुरक्षा सुनिश्चित करना\n• लेनदेन रिकॉर्ड बनाए रखना\n\nहम आपकी जानकारी का उपयोग केवल वैध व्यावसायिक उद्देश्यों के लिए और लागू कानूनों के अनुपालन में करते हैं।',
        'section3Title': '3. जानकारी साझाकरण',
        'section3Content': 'हम निम्नलिखित परिस्थितियों में आपकी जानकारी साझा कर सकते हैं:\n\nअन्य उपयोगकर्ताओं के साथ:\n• लेनदेन उद्देश्यों के लिए व्यावसायिक संपर्क जानकारी\n• उत्पाद सूचियां और विवरण\n• सार्वजनिक प्रोफ़ाइल जानकारी (यदि आप इसे सार्वजनिक बनाना चुनते हैं)\n\nसेवा प्रदाताओं के साथ:\n• लेनदेन हैंडलिंग के लिए भुगतान प्रोसेसर\n• शिपिंग और लॉजिस्टिक्स भागीदार\n• क्लाउड स्टोरेज और होस्टिंग प्रदाता\n• ग्राहक सहायता उपकरण\n• विश्लेषण और विपणन सेवाएं\n\nकानूनी आवश्यकताएं:\n• जब कानून या कानूनी प्रक्रिया द्वारा आवश्यक हो\n• अपने अधिकारों और संपत्ति की सुरक्षा के लिए\n• सुरक्षा की सुरक्षा के लिए आपातकाल के मामले में\n• सरकारी अनुरोधों का अनुपालन करने के लिए\n\nव्यावसायिक स्थानांतरण:\n• विलय, अधिग्रहण, या संपत्ति की बिक्री के मामले में\n• अन्य उद्देश्यों के लिए आपकी स्पष्ट सहमति के साथ\n\nहम कभी भी विपणन उद्देश्यों के लिए तृतीय पक्षों को आपकी व्यक्तिगत जानकारी नहीं बेचते हैं।',
        'section4Title': '4. डेटा सुरक्षा',
        'section4Content': 'सुरक्षा उपाय:\n\n• पारगमन और आराम में डेटा का एन्क्रिप्शन\n• नियमित सुरक्षा अपडेट के साथ सुरक्षित सर्वर\n• पहुंच नियंत्रण और प्रमाणीकरण प्रणाली\n• नियमित सुरक्षा ऑडिट और आकलन\n• डेटा सुरक्षा पर कर्मचारी प्रशिक्षण\n\nतकनीकी सुरक्षा:\n\n• सभी संचार के लिए SSL/TLS एन्क्रिप्शन\n• संवेदनशील संचालन के लिए मल्टी-फैक्टर प्रमाणीकरण\n• नियमित बैकअप और आपदा वसूली प्रक्रियाएं\n• घुसपैठ का पता लगाने और रोकथाम प्रणाली\n• सुरक्षित कोडिंग प्रथाएं और भेद्यता परीक्षण\n\nडेटा उल्लंघन प्रतिक्रिया:\n\n• तत्काल जांच और नियंत्रण\n• 72 घंटों के भीतर प्रभावित उपयोगकर्ताओं को सूचना\n• यदि आवश्यक हो तो कानून प्रवर्तन के साथ सहयोग\n• अतिरिक्त सुरक्षा उपायों का कार्यान्वयन\n• समाधान प्रगति पर नियमित अपडेट\n\nजबकि हम उद्योग-मानक सुरक्षा उपायों को लागू करते हैं, कोई भी प्रणाली 100% सुरक्षित नहीं है। हम लगातार अपनी सुरक्षा प्रथाओं में सुधार करने के लिए काम करते हैं।',
        'section5Title': '5. डेटा प्रतिधारण',
        'section5Content': 'प्रतिधारण अवधि:\n\nखाता जानकारी:\n• सक्रिय खाते: जब तक खाता सक्रिय है तब तक बनाए रखा जाता है\n• बंद खाते: कानूनी अनुपालन के लिए 7 वर्षों तक बनाए रखा जाता है\n• निलंबित खाते: समाधान या स्थायी समापन तक बनाए रखा जाता है\n\nलेनदेन डेटा:\n• भुगतान रिकॉर्ड: कर और कानूनी अनुपालन के लिए 7 वर्ष\n• संचार लॉग: विवाद समाधान के लिए 3 वर्ष\n• उत्पाद सूचियां: खाता समापन या हटाने तक\n\nतकनीकी डेटा:\n• लॉग फाइलें: सुरक्षा और प्रदर्शन निगरानी के लिए 1 वर्ष\n• विश्लेषण डेटा: प्लेटफॉर्म सुधार के लिए 2 वर्ष\n• कुकीज़: हमारी कुकी नीति में निर्दिष्ट के रूप में\n\nकानूनी आवश्यकताएं:\n\n• वित्तीय रिकॉर्ड: न्यूनतम 7 वर्ष\n• पहचान सत्यापन: खाता समापन के बाद 5 वर्ष\n• कानूनी कार्यवाही: समाधान प्लस लागू सीमा अवधि तक\n\nआप कानूनी और परिचालन आवश्यकताओं के अधीन कुछ व्यक्तिगत जानकारी के विलोपन का अनुरोध कर सकते हैं।',
        'section6Title': '6. आपके अधिकार और विकल्प',
        'section6Content': 'आपके अधिकार:\n\nपहुंच और पोर्टेबिलिटी:\n• अपनी व्यक्तिगत जानकारी की प्रतियां अनुरोध करें\n• पोर्टेबल प्रारूप में डेटा प्राप्त करें\n• समझें कि हम आपकी जानकारी का उपयोग कैसे करते हैं\n\nसुधार और अपडेट:\n• गलत व्यक्तिगत जानकारी को सही करें\n• अपनी खाता जानकारी अपडेट करें\n• अपनी गोपनीयता प्राथमिकताएं संशोधित करें\n\nविलोपन और प्रतिबंध:\n• व्यक्तिगत जानकारी के विलोपन का अनुरोध करें\n• अपने डेटा के प्रसंस्करण को प्रतिबंधित करें\n• कुछ डेटा प्रसंस्करण गतिविधियों पर आपत्ति करें\n\nसंचार प्राथमिकताएं:\n• विपणन संचार से बाहर निकलें\n• अ thông báo प्राथमिकताएं चुनें\n• कुकी सेटिंग्स प्रबंधित करें\n\nअपने अधिकारों का उपयोग कैसे करें:\n\n• हमारे सहायता चैनलों के माध्यम से हमसे संपर्क करें\n• बुनियादी प्राथमिकताओं के लिए खाता सेटिंग्स का उपयोग करें\n• जटिल परिवर्तनों के लिए औपचारिक अनुरोध सबमिट करें\n• सुरक्षा सत्यापन के लिए पहचान प्रदान करें\n\nहम सत्यापन और कानूनी आवश्यकताओं के अधीन 30 दिनों के भीतर आपके अनुरोधों का जवाब देंगे।',
        'section7Title': '7. अंतर्राष्ट्रीय डेटा स्थानांतरण',
        'section7Content': 'वैश्विक संचालन:\n\n• हमारा प्लेटफॉर्म दुनिया भर के उपयोगकर्ताओं की सेवा करता है\n• डेटा अंतर्राष्ट्रीय सीमाओं के पार स्थानांतरित किया जा सकता है\n• हम सभी स्थानांतरणों के लिए पर्याप्त सुरक्षा सुनिश्चित करते हैं\n\nस्थानांतरण तंत्र:\n\n• मानक संविदात्मक खंड (SCCs)\n• प्रासंगिक अधिकारियों द्वारा पर्याप्तता निर्णय\n• जहां लागू हो बाध्यकारी कॉर्पोरेट नियम\n• विशिष्ट स्थानांतरण के लिए उपयोगकर्ता सहमति\n\nक्षेत्रीय अनुपालन:\n\nयूरोपीय संघ (GDPR):\n• GDPR आवश्यकताओं के साथ पूर्ण अनुपालन\n• डेटा सुरक्षा अधिकारी नियुक्त\n• डिज़ाइन द्वारा गोपनीयता सिद्धांत लागू\n\nसंयुक्त राज्य अमेरिका:\n• लागू राज्य और संघीय कानूनों का अनुपालन\n• CCPA और अन्य राज्य गोपनीयता कानून अनुपालन\n\nअन्य अधिकार क्षेत्र:\n• जहां लागू हो स्थानीय गोपनीयता कानून अनुपालन\n• नियामक परिवर्तनों की नियमित समीक्षा\n\nहम सुनिश्चित करते हैं कि अंतर्राष्ट्रीय स्थानांतरण डेटा सुरक्षा के उच्चतम मानकों को पूरा करते हैं।',
        'section8Title': '8. कुकीज़ और ट्रैकिंग',
        'section8Content': 'कुकीज़ के प्रकार:\n\nआवश्यक कुकीज़:\n• प्लेटफॉर्म कार्यक्षमता के लिए आवश्यक\n• प्रमाणीकरण और सुरक्षा सुविधाएं\n• शॉपिंग कार्ट और सत्र प्रबंधन\n\nप्रदर्शन कुकीज़:\n• विश्लेषण और उपयोग आंकड़े\n• प्लेटफॉर्म प्रदर्शन निगरानी\n• त्रुटि ट्रैकिंग और डिबगिंग\n\nकार्यात्मक कुकीज़:\n• उपयोगकर्ता प्राथमिकताएं और सेटिंग्स\n• भाषा और स्थानीयकरण\n• बेहतर उपयोगकर्ता अनुभव सुविधाएं\n\nविपणन कुकीज़:\n• विज्ञापन और प्रचार सामग्री\n• उपयोगकर्ता व्यवहार विश्लेषण\n• लक्षित विपणन संचार\n\nकुकी प्रबंधन:\n\n• पहली यात्रा पर कुकी सहमति बैनर\n• कुकी श्रेणियों पर सूक्ष्म नियंत्रण\n• आसान ऑप्ट-आउट तंत्र\n• कुकी उपयोग की नियमित समीक्षा\n\nआप अपने ब्राउज़र सेटिंग्स या हमारे कुकी प्रबंधन उपकरणों के माध्यम से कुकी प्राथमिकताओं को प्रबंधित कर सकते हैं।',
        'section9Title': '9. बच्चों की गोपनीयता',
        'section9Content': 'आयु प्रतिबंध:\n\n• हमारा प्लेटफॉर्म 16 वर्ष से कम उम्र के बच्चों के लिए नहीं है\n• हम जानबूझकर बच्चों से जानकारी एकत्र नहीं करते हैं\n• व्यावसायिक खातों के लिए वयस्क सत्यापन आवश्यक है\n\nमाता-पिता के अधिकार:\n\n• माता-पिता अपने बच्चे के खाते के बारे में जानकारी का अनुरोध कर सकते हैं\n• बच्चे की जानकारी की समीक्षा और हटाने का अधिकार\n• बच्चों से डेटा संग्रह की सूचना\n\nयदि हमें पता चलता है कि हमने माता-पिता की सहमति के बिना बच्चे से जानकारी एकत्र की है, तो हम उस जानकारी को तुरंत हटा देंगे।',
        'section10Title': '10. तृतीय-पक्ष सेवाएं',
        'section10Content': 'एकीकृत सेवाएं:\n\nभुगतान प्रसंस्करण:\n• सुरक्षित भुगतान गेटवे\n• PCI DSS अनुपालन प्रोसेसर\n• लेनदेन प्रसंस्करण के लिए सीमित डेटा साझाकरण\n\nशिपिंग और लॉजिस्टिक्स:\n• अंतर्राष्ट्रीय शिपिंग भागीदार\n• ट्रैकिंग और डिलीवरी सेवाएं\n• सीमा शुल्क और अनुपालन डेटा\n\nविश्लेषण और विपणन:\n• वेबसाइट विश्लेषण प्रदाता\n• विपणन स्वचालन उपकरण\n• ग्राहक संबंध प्रबंधन प्रणाली\n\nतृतीय-पक्ष नीतियां:\n\n• प्रत्येक सेवा की अपनी गोपनीयता नीति है\n• हम गोपनीयता अनुपालन के लिए भागीदारों की जांच करते हैं\n• विशिष्ट उद्देश्यों के लिए सीमित डेटा साझाकरण\n• तृतीय-पक्ष प्रथाओं की नियमित समीक्षा\n\nहम तृतीय-पक्ष सेवाओं की गोपनीयता प्रथाओं के लिए जिम्मेदार नहीं हैं। उपयोगकर्ताओं को एकीकृत सेवाओं का उपयोग करने से पहले तृतीय-पक्ष गोपनीयता नीतियों की समीक्षा करनी चाहिए।',
        'section11Title': '11. गोपनीयता नीति में परिवर्तन',
        'section11Content': 'नीति अपडेट:\n\n• हम इस गोपनीयता नीति को समय-समय पर अपडेट कर सकते हैं\n• महत्वपूर्ण परिवर्तन ईमेल के माध्यम से संचारित किए जाएंगे\n• अपडेट की गई नीतियां हमारी वेबसाइट पर पोस्ट की जाएंगी\n• पिछले संस्करण अनुरोध पर उपलब्ध हैं\n\nसूचना प्रक्रिया:\n\n• भौतिक परिवर्तनों के लिए ईमेल सूचना\n• महत्वपूर्ण अपडेट के लिए वेबसाइट बैनर\n• महत्वपूर्ण परिवर्तनों के लिए खाता सूचना\n• पर्याप्त संशोधनों के लिए 30-दिवसीय नोटिस\n\nउपयोगकर्ता अधिकार:\n\n• अपडेट की गई नीतियों की समीक्षा का अधिकार\n• परिवर्तनों को स्वीकार या अस्वीकार करने का विकल्प\n• परिवर्तनों से असहमत होने पर खाता बंद करने की क्षमता\n• निरंतर उपयोग स्वीकृति का गठन करता है\n\nहम उपयोगकर्ताओं को हमारी प्रथाओं के बारे में सूचित रहने के लिए नियमित रूप से हमारी गोपनीयता नीति की समीक्षा करने के लिए प्रोत्साहित करते हैं।',
        'section12Title': '12. संपर्क जानकारी',
        'section12Content': 'डेटा सुरक्षा अधिकारी:\n\nईमेल: privacy@fruithabibi.com\nफोन: +1 (555) 123-4567\nपता: डेटा सुरक्षा कार्यालय, Fruit Habibi Inc., 123 Business Plaza, Suite 456, San Francisco, CA 94105, USA\n\nसामान्य गोपनीयता पूछताछ:\n\nईमेल: support@fruithabibi.com\nसहायता केंद्र: /help\nसंपर्क फॉर्म: /contact\n\nकानूनी अनुरोध:\n\nईमेल: legal@fruithabibi.com\nकानून प्रवर्तन और कानूनी प्रक्रिया अनुरोधों के लिए\n\nप्रतिक्रिया समय:\n\n• सामान्य पूछताछ: 48 घंटे\n• गोपनीयता अधिकार अनुरोध: 30 दिन\n• कानूनी अनुरोध: कानून द्वारा आवश्यक\n• सुरक्षा घटनाएं: सूचना के लिए 72 घंटे\n\nहम सभी गोपनीयता चिंताओं को तुरंत और पूरी तरह से संबोधित करने के लिए प्रतिबद्ध हैं।'
    }
}

# Update all language files
for lang in ['fr', 'ar', 'hi']:
    file_path = f'src/lib/i18n/translations/{lang}.json'
    
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Update privacy translations
    if lang in privacy_translations:
        if 'privacy' not in data:
            data['privacy'] = {}
        for key, value in privacy_translations[lang].items():
            data['privacy'][key] = value
    
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"{lang.upper()} Privacy translations updated!")

print("Privacy translations for FR and AR completed!")
print("Note: HI, ES, ZH, PT translations will be added in next step due to length.")

